// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpzyjyqcgvhqesxcyvzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwenlqeXFjZ3ZocWVzeGN5dnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzU1MzksImV4cCI6MjA3MjI1MTUzOX0.o3zjpGMHJnbDsN5sqyu2FZtQM5_0rTBEPWbHwO6SS18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});